import { useState } from 'react';
import { Archive, ArrowDownToLine, ArrowUpFromLine, FolderOpen, RefreshCw } from 'lucide-react';
import type { WorkspaceState } from '../shared/types';
import type { DesktopManifest } from '../shared/desktop';
import * as api from './api';
import { SyncPanel } from './SyncPanel';
type Toast = { kind: 'success' | 'error'; text: string };
type ArchiveChoice = { base64?: string; archiveToken?: string; name: string; manifest: DesktopManifest };
export function SettingsPanel({ state, onRefresh, onRebuild, onToast, readOnly }: { state: WorkspaceState; onRefresh: () => void; onRebuild: () => void | Promise<void>; onToast: (toast: Toast) => void; readOnly: boolean }) {
  const [busy, setBusy] = useState(false), [archive, setArchive] = useState<ArchiveChoice>();
  const [target, setTarget] = useState<{ token: string; displayPath: string }>();
  const desktop = window.academicDesktop;
  const action = async (work: () => Promise<string | false | void>, success?: string) => { setBusy(true); try { const result = await work(); if (result !== false && success) onToast({ kind: typeof result === 'string' ? 'error' : 'success', text: typeof result === 'string' ? `${success}；${result}` : success }); } catch (error) { onToast({ kind: 'error', text: error instanceof Error ? error.message : '操作失败，原资料已保留' }); } finally { setBusy(false); } };
  const chooseNative = async () => { setArchive(undefined); setTarget(undefined); const selected = await desktop!.chooseRestoreArchive(); if (!selected.canceled) setArchive({ archiveToken: selected.archiveToken, name: '已选择并校验的本地备份', manifest: selected.manifest }); };
  const chooseWeb = async (file: File) => { setArchive(undefined); setTarget(undefined); const base64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] || ''); reader.onerror = () => reject(new Error('读取备份失败')); reader.readAsDataURL(file); }); const { manifest } = await api.inspectRestore(base64); setArchive({ base64, name: file.name, manifest }); };
  return <><div className="page-header"><div><div className="eyebrow">资料安全</div><h1>资料与设置</h1><p>了解资料在哪里，随时带走一份完整备份。</p></div></div><div className="settings-grid">
    <section className="card settings-card"><div className="settings-heading"><div className="setting-icon"><FolderOpen size={19} /></div><div><h2>本地资料目录</h2><p>所有笔记、文献和研究记录都保存在这台电脑上。</p></div></div><dl className="detail-list"><div><dt>目录</dt><dd title={state.dataDirectory}>{state.dataDirectory}</dd></div><div><dt>占用空间</dt><dd>{(state.storageBytes / 1024 / 1024).toFixed(2)} MB</dd></div><div><dt>运行环境</dt><dd>{desktop ? `桌面应用 · ${state.platformLabel}` : state.platformLabel}</dd></div><div><dt>索引状态</dt><dd>{state.indexStatus === 'ready' ? '已就绪' : '需要重建'}</dd></div></dl><div className="settings-index-actions"><button className="button secondary" onClick={onRefresh}><RefreshCw size={16} />刷新状态</button><button className="button secondary" disabled={readOnly || busy} onClick={() => void onRebuild()}>重建索引</button></div></section>
    <section className="card settings-card"><div className="settings-heading"><div className="setting-icon mint"><Archive size={19} /></div><div><h2>完整备份</h2><p>{readOnly ? '只读实例不能生成稳定完整备份，请在可写实例中生成。' : '包括正文、文献元信息、待办、日程、PDF 与恢复资料。'}</p></div></div><div className="backup-actions"><button className="button primary" disabled={busy || readOnly} onClick={() => void action(async () => { if (desktop) { if ((await desktop.backup()).canceled) return false; } else api.saveBlob(await api.createBackup(), `研笺备份-${new Date().toISOString().slice(0,10)}.zip`); }, '备份已生成并通过校验')}><ArrowDownToLine size={16} />{readOnly ? '请在可写实例中备份' : desktop ? '保存完整备份' : '下载本地备份'}</button>
      {desktop ? <button className="button secondary" disabled={readOnly || busy} onClick={() => void action(chooseNative)}><ArrowUpFromLine size={16} />选择备份恢复</button> : <label className={`button secondary ${readOnly ? 'disabled' : ''}`}><ArrowUpFromLine size={16} />选择备份恢复<input type="file" accept=".zip,application/zip" hidden disabled={readOnly || busy} onChange={e => { const file = e.target.files?.[0]; if (file) void action(() => chooseWeb(file)); e.currentTarget.value = ''; }} /></label>}</div>
      {archive && <div className="restore-review"><strong>{archive.name}</strong><span>{archive.manifest.files.length} 个文件 · 创建于 {new Date(archive.manifest.createdAt).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' })}</span>
        {desktop ? <><button className="button secondary" disabled={busy || readOnly} onClick={() => void action(async () => { const choice = await desktop.chooseRestoreTarget(); if (!choice.canceled) setTarget({ token: choice.targetToken, displayPath: choice.displayPath }); })}>选择恢复空目录</button><span>{target?.displayPath || '尚未选择恢复目录'}</span></> : <label>目标空目录路径<input disabled={readOnly || busy} value={target?.displayPath || ''} onChange={e => setTarget({ token: '', displayPath: e.target.value })} placeholder="输入已选择的空目录路径" /></label>}
        <p>恢复到独立空目录，校验成功后切换；原资料目录保留。</p><button className="button primary" disabled={readOnly || busy || !target?.displayPath} onClick={() => void action(async () => { let warning: string | undefined; if (desktop) { const result = await desktop.restore(archive.archiveToken!, target!.token); if (result.canceled) return false; warning = result.cleanupWarning; } else { const chosen = target?.token ? target : await api.chooseRestoreTarget(target!.displayPath); warning = (await api.restore(archive.base64!, chosen.token)).cleanupWarning; } setArchive(undefined); setTarget(undefined); onRefresh(); return warning; }, '恢复完成，应用将使用新的资料目录')}>开始恢复</button></div>}
    </section></div><SyncPanel key={state.dataDirectory} readOnly={readOnly} onRefresh={onRefresh} /></>;
}
